SRC =	validation.c \
		map_validations.c \
		create_map.c \
		check_if_map_index_exists.c \
		textures.c \
		helpers.c \
		helpers_2.c \

all:
	gcc   $(SRC) ../ray_caster/get_next_line.c ../ray_caster/get_next_line_utils.c ../../libraries/libft.a