SRC =	validation.c \
		map_validations.c \
		create_map.c \
		check_if_map_index_exists.c \
		textures.c \
		helpers.c \
		helpers_2.c \

all:
	gcc   $(SRC) ../../get_next_line.c ../../get_next_line_utils.c ../../libft.a